# Publish NPM package to npmjs.com pipeline
name: Publish NPM package

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
          registry-url: 'https://registry.npmjs.org'

      - name: install packages
        run: yarn install

      - name: read "publish" tag
        run: |
          echo "publish=false" >> $GITHUB_ENV

          # Get your last commit message, not the merge commit.
          text=$(git log -1 --no-merges --pretty=%B)

          echo "commit msg: ${text}"

          # Read the commit message into an array split by "#".
          readarray -d "#" -t commit_message <<< "$text"

          echo "tag: ${commit_message[1]}"

          # Check if "publish" tag exists and set env variable
          if [[ "${commit_message[1]}" == *"publish"*  ]]; then
            echo "publish=true" >> $GITHUB_ENV
          fi

      - uses: JS-DevTools/npm-publish@v1
        if: ${{ env.publish == 'true' }}
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: 'public'
          dry-run: false